# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'RevatureDogs-project2'
    organization: '2002-feb24-net'
    scannerMode: 'MSBuild'
    projectKey: '2002-feb24-net_RevatureDogs-project2'
    projectName: 'RevatureDogs-project2'

- script: dotnet build
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure-RevatureDogs-project2'
    appType: 'webApp'
    WebAppName: 'RevatureDogs-project2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'