# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: dotnet build
  workingDirectory: RevDogs
  displayName: dotnet build

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure-RevatureDogs-project2'
    appType: 'webApp'
    WebAppName: 'RevatureDogs-project2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'